//! Logins, held in memory and keyed by the CRSESSID cookie — the same shape
//! as the V app's `sessions` map. Restarting drops every session, which is
//! what the original does too.

use std::collections::HashMap;
use std::sync::Mutex;

use crate::db::Db;

pub const SESSION_COOKIE: &str = "CRSESSID";

#[derive(Debug, Clone)]
pub struct SessionUser {
    /// stamped onto a build once the planner lands (see PORTING.md)
    #[allow(dead_code)]
    pub id: i64,
    pub username: String,
    pub is_admin: bool,
}

#[derive(Debug)]
pub struct Sessions {
    inner: Mutex<HashMap<String, Entry>>,
}

/// A session dies after this long even if its cookie survives: without an
/// issue time every login lived until process restart and the map grew
/// monotonically. Matches the 7-day cap the V app carried.
const SESSION_TTL_SECS: i64 = 7 * 24 * 3600;

#[derive(Debug)]
struct Entry {
    user: SessionUser,
    issued: i64,
}

impl Sessions {
    pub fn new() -> Self {
        Self { inner: Mutex::new(HashMap::new()) }
    }

    /// Starts a session and returns its key, which becomes the cookie value.
    /// Expired entries are swept on the way in, so the map cannot grow
    /// without bound.
    pub fn start(&self, user: SessionUser) -> String {
        let key = uuid::Uuid::new_v4().to_string();
        let now = now_unix();
        if let Ok(mut map) = self.inner.lock() {
            map.retain(|_, e| now.saturating_sub(e.issued) <= SESSION_TTL_SECS);
            map.insert(key.clone(), Entry { user, issued: now });
        }
        key
    }

    pub fn get(&self, key: &str) -> Option<SessionUser> {
        let mut map = self.inner.lock().ok()?;
        let issued = map.get(key)?.issued;
        if now_unix().saturating_sub(issued) > SESSION_TTL_SECS {
            // a stale token must not authenticate anyone; drop it so it also
            // cannot be replayed after the sweep would have caught it
            map.remove(key);
            return None;
        }
        map.get(key).map(|e| e.user.clone())
    }

    pub fn end(&self, key: &str) {
        if let Ok(mut map) = self.inner.lock() {
            map.remove(key);
        }
    }
}

fn now_unix() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |d| i64::try_from(d.as_secs()).unwrap_or(0))
}

/// `Argon2id` in PHC string format, generated by `SurrealDB`'s own
/// `crypto::argon2::generate` — the app carries no crypto dependency and a
/// hash made by the V app (same PHC shape) still verifies in `compare`.
/// The salt is the server's, so two hashes of one password differ.
pub async fn hash_password(db: &Db, password: &str) -> Result<String, surrealdb::Error> {
    let mut res = db
        .query("RETURN crypto::argon2::generate($p)")
        .bind(("p", password.to_string()))
        .await?;
    res.take::<Option<String>>(0)?.ok_or_else(|| {
        surrealdb::Error::validation("argon2::generate returned nothing".to_string(), None)
    })
}

/// Verifies a password against a PHC hash via `crypto::argon2::compare`.
/// Malformed hashes compare false rather than erroring, and so does a
/// transport error — the caller only needs the verdict.
pub async fn verify_password(db: &Db, password: &str, hash: &str) -> bool {
    matches!(
        db.query("RETURN crypto::argon2::compare($h, $p)")
            .bind(("h", hash.to_string()))
            .bind(("p", password.to_string()))
            .await
            .and_then(|mut r| r.take::<Option<bool>>(0)),
        Ok(Some(true))
    )
}

/// Burns roughly the time a real verification costs, so a missing username
/// cannot be told from a wrong password by how fast the answer comes back.
/// The V login does the same with a throwaway generate-then-compare.
pub async fn waste_time(db: &Db, password: &str) {
    if let Ok(h) = hash_password(db, password).await {
        verify_password(db, password, &h).await;
    }
}
